name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t flight-predictor-test .

      - name: Run Tests in Container
        run: docker run --rm flight-predictor-test poetry run pytest tests/